name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and contexts by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
    runs-on-issues-and-prs:
        runs-on: ubuntu latest
        # if: github.event_name == 'issues' || github.event_name == 'pull_request'
        if: contains(fromJson('["issues", "pull_requests"]'), github.event_name)
        steps:
            - name: Run only if issue has bug label
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name, ', ')}}
    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expression
              id: expression
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string'=='String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'
