name: variables and secrets
on: [push]

jobs:
    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        steps:
            - name: run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "i ran"
            - name: log vars
              run: |
                echo '${{ vars.JOBS_RUNNER }}'
                echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"