name: Working Dirs & shells
on: [push]

jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory and list files
              run: |
                pwd
                la -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    isplay-wd-info-windows:
      runs-on: windows-latest
      steps:
          - name: Display working directory and list files
            run: |
              pwd
              la -a
              echo $GITHUB_SHA
              echo $GITHUB_REPOSITORY
              echo $GITHUB_WORKSPACE